language: node_js
node_js: 
  - "12"
cache:
  yarn: true
  directories:
    - "node_modules"
services:
  - docker

env:
  global:
    - IMAGE_NAME=continuous-improvement/event-service

stages:
  - build
  - docker-build
  - test

before_script:
  # Move to source directory
  - cd src

jobs:
  include:
    - stage: build
      script:
        # Install dependencies
        - yarn install
        # Build source
        - yarn build
    - stage: docker-build
      script:
        # Build docker image
        - docker build -t $IMAGE_NAME .
        # List docker images
        - docker images
    - stage: test
      script:
        # Install dependencies
        - yarn install
        # Run tests
        - yarn test --passWithNoTests
