apiVersion: v1
kind: Service
metadata:
  name: prod-event-service
  namespace: production
  labels:
    app: prod-event-service
spec:
  selector:
    app: prod-event-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
